# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: xenial

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # Latest dependencies on macOS with MKL
    - env: DISTRIB="conda" PYTHON_VERSION="*" INSTALL_MKL="true"
           NUMPY_VERSION="*" SCIPY_VERSION="*" CYTHON_VERSION="*"
           PILLOW_VERSION="*" JOBLIB_VERSION="*" COVERAGE=true
      language: generic
      if: type != cron
      os: osx
    # Linux environment to test that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Xenial 16.04
    # i.e. numpy 1.11 and scipy 0.17
    - env: DISTRIB="ubuntu" PYTHON_VERSION="3.5"
           NUMPY_VERSION="1.11.0" SCIPY_VERSION="0.17.0"
           PILLOW_VERSION="4.0.0" COVERAGE=true
           SKLEARN_SITE_JOBLIB=1 JOBLIB_VERSION="0.11"
      if: type != cron
      addons:
        apt:
          packages:
            # these only required by the DISTRIB="ubuntu" builds:
            - python3-scipy
            - libatlas3-base
            - libatlas-base-dev
            - libatlas-dev
    # Linux + Python 3.5 build with OpenBLAS and without SITE_JOBLIB
    - env: DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="false"
           NUMPY_VERSION="1.11.0" SCIPY_VERSION="0.17.0" CYTHON_VERSION="*"
           PILLOW_VERSION="4.0.0" COVERAGE=true
      if: type != cron
    # Linux environment to test the latest available dependencies and MKL.
    # It runs tests requiring pandas and PyAMG.
    # It also runs with the site joblib instead of the vendored copy of joblib.
    - env: DISTRIB="conda" PYTHON_VERSION="*" INSTALL_MKL="true"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           CYTHON_VERSION="*" PYAMG_VERSION="*" PILLOW_VERSION="*"
           JOBLIB_VERSION="*" COVERAGE=true
           CHECK_PYTEST_SOFT_DEPENDENCY="true" TEST_DOCSTRINGS="true"
           SKLEARN_SITE_JOBLIB=1 CHECK_WARNINGS="true"
      if: type != cron
    # Linux environment to test scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    -  python: 3.7
       env: DISTRIB="scipy-dev" CHECK_WARNINGS="true"
       if: type = cron OR commit_message =~ /\[scipy-dev\]/

install: source build_tools/travis/install.sh
script: 
  - bash build_tools/travis/test_script.sh
  - bash build_tools/travis/test_docs.sh
  - bash build_tools/travis/test_pytest_soft_dependency.sh
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
